### ISSUE TITLE
Not able to ssh after hardening of Ubuntu OS

### ISSUE THREAD

**Issue by vivekbangare** [ansible-lockdown/UBUNTU22-CIS#170] opened 2023-11-13 11:28 UTC
**Question**

After applying for UBUNTU22-CIS roles, I cannot SSH after the reboot of Ubuntu 22, what's needs to be done to fix the issue?

**Environment :**

- Ansible Version: [ 2.14.6 ]
- Host Python Version: [ Python 3.9.18 ]
- Ansible Server Python Version: [ Python 3.9.18 ]
- Additional Details: I am creating golden image AMI with the help of UBUNTU-CIS roles, but as soon as all tasks completed and I took restart of machine, I am not able to login to my new machine.

**Comment by dhoppe** [comment] 2023-11-14 21:10
@uk-bolly I am not sure if this will negatively affect performance, but I think it makes sense to add `validate: 'sshd -t -f %s'` to the `ansible.builtin.lineinfile` tasks in `tasks/section_5/cis_5.2.x.yml` instead of relying on whether the restart of SSH via `handlers/main.yml` fails or not.

**Comment by twadelij** [comment] 2023-11-20 07:27
Hi @uk-bolly,
It looks like rule ubtu22cis_rule_5_2_13/14/15 change the /etc/ssh/sshd/config with some weird commas

Examples:
#MACs h,m,a,c,-,s,h,a,2,-,5,1,2,-,e,t,m,@,o,p,e,n,s,s,h,.,c,o,m,,,h,m,a,c,-,s,h,a,2,-,2,5,6,-,e,t,m,@,o,p,e,n,s,s,h,.,c,o,m,,,h,m,a,c,-,s,h,a,2,-,5,1,2,,,h,m,a,c,-,s,h,a,2,-,2,5,6
#Ciphers c,h,a,c,h,a,2,0,-,p,o,l,y,1,3,0,5,@,o,p,e,n,s,s,h,.,c,o,m,,,a,e,s,2,5,6,-,g,c,m,@,o,p,e,n,s,s,h,.,c,o,m,,,a,e,s,1,2,8,-,g,c,m,@,o,p,e,n,s,s,h,.,c,o,m,,,a,e,s,2,5,6,-,c,t,r,,,a,e,s,1,9,2,-,c,t,r,,,a,e,s,1,2,8,-,c,t,r
Which breaks ssh after the deamon restarts. So only access through the console works.
Can you change this question into an issue or do I create a separate one?

After setting these rules to false and running the hardening again. I could logon again.

Regards 
Ted

**Comment by uk-bolly** [comment] 2023-11-20 08:52
> @uk-bolly I am not sure if this will negatively affect performance, but I think it makes sense to add `validate: 'sshd -t -f %s'` to the `ansible.builtin.lineinfile` tasks in `tasks/section_5/cis_5.2.x.yml` instead of relying on whether the restart of SSH via `handlers/main.yml` fails or not.

Hi @dhoppe 

Happy to add a validate to this Will add to the next issues.

Thanks

uk-bolly

**Comment by uk-bolly** [comment] 2023-11-20 08:54
hi @vivekbangare and @twadelij 

Could you let me know which branches and releases you are using? I have run this without error using the devel and main branches.
I will add the validate to as suggested by @dhoppe.
Very keen to get to the bottom of where this is occuring.

Many thanks

uk-bolly

**Comment by twadelij** [comment] 2023-11-20 09:21
Hi @uk-bolly 
For Ubuntu22 i'm currently on the latest devel branch
Thinking about switching to main this week

**Comment by uk-bolly** [comment] 2023-11-20 09:32
hi @twadelij 

Thank you for the quick response.
Could you let me know the version of ansible you are running? and jinja2 you are running?
I am not able to reproduce the issue based on the default configurations.
I have also pushed up a new branch ready for a PR thats includes the validate.

thanks

uk-bolly

**Comment by twadelij** [comment] 2023-11-20 14:35
Hi @uk-bolly 
Still very old I'm afraid:
Ansible 2.9.27
Jinja2 2.7.2

**Comment by uk-bolly** [comment] 2023-11-20 14:44
hi @twadelij 

Sorry we haven't support 2.9 for a while and ansible stopped supporting it a long time ago. If you are able to reproduce to with a later version, very happy to follow this up as i am concerned some people experiencing issues i am not able to replicate.

Many thanks

uk-bolly

**Comment by dderemiah** [comment] 2023-12-28 01:25
Just in case anyone sees this sshd failure.  The ssh config options changed from a list to a dictionary.  Look in defaults/main.yml for an example of the proper formatting of that setting in your vars file.

**Comment by uk-bolly** [comment] 2024-01-09 16:59
hi @vivekbangare 

Is this now working as expected?
A validate was added to each sshd control to test the config prior to committing the change. I hope this has now fixed your issue?

many thanks

uk-bolly

**Comment by uk-bolly** [comment] 2024-04-09 08:22
hi @vivekbangare 

I believe that this issue has been addressed and the fix merged?
I will close this issue, please feel free to reopen or raise a new one if this particular problem still exists.

Many thanks

uk-bolly

**Closed by uk-bolly** 2024-04-09 08:22 UTC
Labels: question
